hw/hw07/ByteCraftMaster/07_1_task1.py
hw/hw07/ByteCraftMaster/07_1_task2.py
hw/hw07/ByteCraftMaster/07_1_task3.py
hw/hw07/ByteCraftMaster/07_3_task_1.py
hw/hw07/ByteCraftMaster/07_3_task_10.py
hw/hw07/ByteCraftMaster/07_3_task_11.py
hw/hw07/ByteCraftMaster/07_3_task_12.py
hw/hw07/ByteCraftMaster/07_3_task_2.py
hw/hw07/ByteCraftMaster/07_3_task_3.py
hw/hw07/ByteCraftMaster/07_3_task_4.py
hw/hw07/ByteCraftMaster/07_3_task_5.py
hw/hw07/ByteCraftMaster/07_3_task_6.py
hw/hw07/ByteCraftMaster/07_3_task_7.py
hw/hw07/ByteCraftMaster/07_3_task_8.py
hw/hw07/ByteCraftMaster/07_3_task_9.py

This pull request contain 07.1 Practical tasks for HW07

HW07: Add 07.1 Practical tasks - ByteCraftMaster

---

hw/hw07/lians/i_jenny.py
hw/hw07/lians/ii_distance.py
hw/hw07/lians/iii_no_yelling.py
hw/hw07/lians/iv_num_str.py
hw/hw07/lians/ix_banjo.py
hw/hw07/lians/v_reverse_words.py
hw/hw07/lians/vi_reverse_list.py
hw/hw07/lians/vii_multiples.py
hw/hw07/lians/viii_make_it.py
hw/hw07/lians/x_boolean.py
hw/hw07/lians/xi_sheeps.py
hw/hw07/lians/xii_tail.py

Added solutions for optional tasks, part 2.

HW07: optional tasks Lians

---

Zen.txt

changed line 64

---

Zen.txt

change zen

---

hw/hw08/NightOutlaw/08.1/main.py
hw/hw08/NightOutlaw/08.1/models/__init__.py
hw/hw08/NightOutlaw/08.1/models/admin.py
hw/hw08/NightOutlaw/08.1/models/user.py
hw/hw08/NightOutlaw/08.1/utils/__init__.py
hw/hw08/NightOutlaw/08.1/utils/formatter.py
hw/hw08/NightOutlaw/08.1/utils/logger.py
hw/hw08/NightOutlaw/08.2/08_2.py
hw/hw08/NightOutlaw/08.3/areas.py
hw/hw08/NightOutlaw/08.3/main.py

Цей пулреквест містить скріпти вирішення для домашнього завдання HW08.

HW08: Add solutions for homework tasks for NightOutlaw

---

Zen.txt

HW6.1-editZen-yuliaklimchuk

---

Zen.txt

Replaced the nickname with the roww of Python Zen

Updated 'Zen.txt'

---

Zen.txt

Додав рядок з Zen of Python

---

hw/hw08/hw08_3/ivze0115/area_func.py
hw/hw08/hw08_3/ivze0115/main.py

Added 08.3 Practical task GitHub Topic 8 for ivze0115

HW08_3: Added 08.3 Practical task GitHub Topic 8 for ivze0115

---

hw/hw07/olymp7/task1_1.py
hw/hw07/olymp7/task1_2.py
hw/hw07/olymp7/task1_3.py
hw/hw07/olymp7/task3_1.py
hw/hw07/olymp7/task3_10.py
hw/hw07/olymp7/task3_11.py
hw/hw07/olymp7/task3_12.py
hw/hw07/olymp7/task3_2.py
hw/hw07/olymp7/task3_3.py
hw/hw07/olymp7/task3_4.py
hw/hw07/olymp7/task3_5.py
hw/hw07/olymp7/task3_6.py
hw/hw07/olymp7/task3_7.py
hw/hw07/olymp7/task3_8.py
hw/hw07/olymp7/task3_9.py
hw/hw08/olymp7/08_1_Practical_task/main.py
hw/hw08/olymp7/08_1_Practical_task/models/__init__.py
hw/hw08/olymp7/08_1_Practical_task/models/admin.py
hw/hw08/olymp7/08_1_Practical_task/models/user.py
hw/hw08/olymp7/08_1_Practical_task/utils/__init__.py
hw/hw08/olymp7/08_1_Practical_task/utils/formatter.py
hw/hw08/olymp7/08_1_Practical_task/utils/logger.py
hw/hw08/olymp7/08_2_Practical_task/check_password.py
hw/hw08/olymp7/08_3_Practical_task/area.py
hw/hw08/olymp7/08_3_Practical_task/main.py

Add HW08 for olymp7

---

hw/hw09/ivze0115/task_09_2/Practical_Tasks_GitHub_Topic_9_09_2_Rect_pygame.py

Added 09.2 Practical task GitHub Topic 9 for ivze0115

HW09_2: Added 09.2 Practical task GitHub Topic 9 for ivze0115

---

hw/hw08/Astronaut-08/08.1 Practical task/main.py
hw/hw08/Astronaut-08/08.1 Practical task/models/__init__.py
hw/hw08/Astronaut-08/08.1 Practical task/models/admin.py
hw/hw08/Astronaut-08/08.1 Practical task/models/user.py
hw/hw08/Astronaut-08/08.1 Practical task/utils/__init__.py
hw/hw08/Astronaut-08/08.1 Practical task/utils/formatter.py
hw/hw08/Astronaut-08/08.1 Practical task/utils/logger.py
hw/hw08/Astronaut-08/08.2 Practical task/main.py
hw/hw08/Astronaut-08/08.3 Practical task/areas.py
hw/hw08/Astronaut-08/08.3 Practical task/main.py
hw/hw09/Astronaunt-08/09.1_Practical_task/rangom_game.py
hw/hw09/Astronaunt-08/09.1_practical_task/random_game.py
hw/hw09/Astronaunt-08/09.2_practical_task/Rect_pygame.py

Hw09 astronaut 08

---

hw/hw09/saudeawd/correct_game_task2.py
hw/hw09/saudeawd/game_task1.py

This pull request contains game and corrected code that was given.

HW09: Added two tasks from week 9, game with guessing number and corrected code. 

---

hw/hw07/VikaLiakh/codewars_tasks.py
hw/hw07/VikaLiakh/task_1.py
hw/hw07/VikaLiakh/task_2.py
hw/hw07/VikaLiakh/task_3.py

Hello, here is my hw 7 - 3 tasks from 07.1 Practical_tasks part

HW 7 by VikaLiakh

---

hw/hw07/VasiaZozulia/I. Jennys secret message.py
hw/hw07/VasiaZozulia/II. Find The Distance Between Two Points.py
hw/hw07/VasiaZozulia/III. No yelling.py
hw/hw07/VasiaZozulia/IV. Convert a Number to a String.py
hw/hw07/VasiaZozulia/IX. Are you Playing Banjo.py
hw/hw07/VasiaZozulia/V. Reversing Words in a String.py
hw/hw07/VasiaZozulia/VI. Reverse List Order.py
hw/hw07/VasiaZozulia/VII. Multiply of 3 or 5.py
hw/hw07/VasiaZozulia/VIII. Will you make it.py
hw/hw07/VasiaZozulia/X. Convert boolean values to strings Yes or No.py
hw/hw07/VasiaZozulia/XI. Counting sheep.py
hw/hw07/VasiaZozulia/XII. Is this my tail.py

Hw07: 07.3 Practical Tasks - VasiaZozulia

---

hw/hw08/VasiaZozulia/08.1/main.py
hw/hw08/VasiaZozulia/08.1/models/__init__.py
hw/hw08/VasiaZozulia/08.1/models/admin.py
hw/hw08/VasiaZozulia/08.1/models/user.py
hw/hw08/VasiaZozulia/08.1/utils/__init__.py
hw/hw08/VasiaZozulia/08.1/utils/formatter.py
hw/hw08/VasiaZozulia/08.1/utils/logger.py
hw/hw08/VasiaZozulia/08.2/password_validation.py
hw/hw08/VasiaZozulia/08.3/Task2.py
hw/hw08/VasiaZozulia/08.3/figures_area.py

hw08: 08.1 Practical task - Vasia Zozulia

---

hw/hw07/ivansstef/07_1 Practical tasks-1.py
hw/hw07/ivansstef/07_1 Practical tasks-2.py
hw/hw07/ivansstef/07_1 Practical tasks-3.py
hw/hw07/ivansstef/07_3 Practical tasks-01.py
hw/hw07/ivansstef/07_3 Practical tasks-02.py
hw/hw07/ivansstef/07_3 Practical tasks-03.py
hw/hw07/ivansstef/07_3 Practical tasks-04.py
hw/hw07/ivansstef/07_3 Practical tasks-05.py
hw/hw07/ivansstef/07_3 Practical tasks-06.py
hw/hw07/ivansstef/07_3 Practical tasks-07.py
hw/hw07/ivansstef/07_3 Practical tasks-08.py
hw/hw07/ivansstef/07_3 Practical tasks-09.py
hw/hw07/ivansstef/07_3 Practical tasks-10.py
hw/hw07/ivansstef/07_3 Practical tasks-11.py
hw/hw07/ivansstef/07_3 Practical tasks-12.py
hw/hw08/ivansstef/task 08.1/main.py
hw/hw08/ivansstef/task 08.1/models/__init__.py
hw/hw08/ivansstef/task 08.1/models/admin.py
hw/hw08/ivansstef/task 08.1/models/user.py
hw/hw08/ivansstef/task 08.1/utils/__init__.py
hw/hw08/ivansstef/task 08.1/utils/formatter.py
hw/hw08/ivansstef/task 08.1/utils/logger.py
hw/hw08/ivansstef/task 08.2/valid_pass.py
hw/hw08/ivansstef/task 08.3/calculate.py
hw/hw08/ivansstef/task 08.3/main.py

@lhalam 
_Просили  тато, просила  мама_ 
змерджіть  в **main**,
якщо:
-  все добре
-  все правильно
-  все чудово
Тому що:
- [ 👍  ] код написаний
- [ 👍 ] структура сформована
- [ 👍 ] гілка створена
- [ 👍 ] файли додані
- [ 👍 ]  комміт написаний
- [ 👍 ] усе запушано
`print ("Molodec"`)
[прекрасна гілка - hw08-ivansstef - тут](https://github.com/EmpowerU-Python-Fundamentals/EmpowerUPythonFundamentals/tree/hw08-ivansstef)
markdown test  done :)

Hw08 ivansstef

---

hw/hw08/VikaLiakh/task1/main.py
hw/hw08/VikaLiakh/task1/models/__init__.py
hw/hw08/VikaLiakh/task1/models/admin.py
hw/hw08/VikaLiakh/task1/models/user.py
hw/hw08/VikaLiakh/task1/utils/__init__.py
hw/hw08/VikaLiakh/task1/utils/formatter.py
hw/hw08/VikaLiakh/task1/utils/logger.py
hw/hw08/VikaLiakh/task2/task2.py
hw/hw08/VikaLiakh/task3/areas.py
hw/hw08/VikaLiakh/task3/main.py

Hello:) Here is my homework from lesson 8.

HW8 by VikaLiakh

---

hw/hw08/dimonstools/08_1/main.py
hw/hw08/dimonstools/08_1/models/__init__.py
hw/hw08/dimonstools/08_1/models/admin.py
hw/hw08/dimonstools/08_1/models/user.py
hw/hw08/dimonstools/08_1/utils/__init__.py
hw/hw08/dimonstools/08_1/utils/formatter.py
hw/hw08/dimonstools/08_1/utils/logger.py
hw/hw08/dimonstools/08_2/main.py
hw/hw08/dimonstools/08_3/calculate.py
hw/hw08/dimonstools/08_3/main.py

Here are the results for [08. Modules and Packages](https://softserve.academy/course/section.php?id=6016) tasks

HW08: Add results for task #8 for dimonstools

---

hw/hw09/Serg-Pro/Rect_pygame.py
hw/hw09/Serg-Pro/task_9_1.py

Цей пулреквест містить Python файли таски1 і 2 для домашнього завдання HW09.

HW09: Add task 1 and task 2 for Serg-Pro

---

hw/hw10/lians/tasks_01/employee.py
hw/hw10/lians/tasks_01/human.py
hw/hw10/lians/tasks_01/polygon.py
hw/hw10/lians/tasks_02/adam_eve.py
hw/hw10/lians/tasks_02/ball.py
hw/hw10/lians/tasks_02/classy.py
hw/hw10/lians/tasks_02/color_ghosts.py
hw/hw10/lians/tasks_02/dynamic.py
hw/hw10/lians/tasks_02/spheres.py

1. Added 10.2 Practical Tasks / [GitHub] [Outside].
2. Added 10.1 Practical tasks / [GitHub].

HW10: practical tasks for Lians

---

hw/hw09/WorkTimwan/Task02/Task02.py

add task02 from lhomework09 from WorkTimwan

HW09: Task02 - WorkTimwan

---

hw/hw07/f00a0a/task_7.1/task_1.py
hw/hw07/f00a0a/task_7.1/task_2.py
hw/hw07/f00a0a/task_7.1/task_3.py

Hw07 f00a0a

---

hw/hw09/ByteCraftMaster/09_1_Practical task.py
hw/hw09/ByteCraftMaster/09_2_Practical task.py

This pull request contains  09.1 and 09.2 practical tasks

HW09: Add 09.1 and 09.2 practical tasks - ByteCraftMaster

---

hw/hw09/NightOutlaw/09.1/main.py
hw/hw09/NightOutlaw/09.2/Rect_pygame.py

Додав рішення для домашнього завдання за темою №9

HW09: Add homework task solution for NightOutlaw

---

hw/hw08/inna-rst/task 8.1/main.py
hw/hw08/inna-rst/task 8.1/models/__init__.py
hw/hw08/inna-rst/task 8.1/models/admin.py
hw/hw08/inna-rst/task 8.1/models/user.py
hw/hw08/inna-rst/task 8.1/utils/__init__.py
hw/hw08/inna-rst/task 8.1/utils/formatter.py
hw/hw08/inna-rst/task 8.1/utils/logger.py
hw/hw08/inna-rst/task 8.3/m_area.py
hw/hw08/inna-rst/task 8.3/main.py
hw/hw08/inna-rst/task8.2_validator_password.py

This pull request includes solutions for tasks 8.1 - 8.3 for HW08.

HW08: Add solutions for tasks 8.1-8.3

---

hw/hw10/ivze0115/task_10_2/Practical_Tasks_GitHub_Topic_10_2_Outside_task1_Ball-super-ball.py
hw/hw10/ivze0115/task_10_2/Practical_Tasks_GitHub_Topic_10_2_Outside_task2_Color-ghost.py
hw/hw10/ivze0115/task_10_2/Practical_Tasks_GitHub_Topic_10_2_Outside_task3_Basic-subclasses-Adam-and-Eve.py
hw/hw10/ivze0115/task_10_2/Practical_Tasks_GitHub_Topic_10_2_Outside_task4_Classy-classes.py
hw/hw10/ivze0115/task_10_2/Practical_Tasks_GitHub_Topic_10_2_Outside_task5_Building_Spheres.py
hw/hw10/ivze0115/task_10_2/Practical_Tasks_GitHub_Topic_10_2_Outside_task6_Dynamic_Classes.py

Add 10.2 Practical tasks GitHub Outside for ivze0115

HW10_2: Add 10.2 Practical tasks GitHub Outside for ivze0115

---

hw/hw08/Eugen1017/tsk1/main.py
hw/hw08/Eugen1017/tsk1/models/__init__.py
hw/hw08/Eugen1017/tsk1/models/admin.py
hw/hw08/Eugen1017/tsk1/models/user.py
hw/hw08/Eugen1017/tsk1/utils/__init__.py
hw/hw08/Eugen1017/tsk1/utils/formatter.py
hw/hw08/Eugen1017/tsk1/utils/logger.py
hw/hw08/Eugen1017/tsk2/get_check_pword/auth.py
hw/hw08/Eugen1017/tsk2/get_check_pword/validate_pass.py
hw/hw08/Eugen1017/tsk2/main.py
hw/hw08/Eugen1017/tsk3/calc_area/areas.py
hw/hw08/Eugen1017/tsk3/calc_area/get_calc_area.py
hw/hw08/Eugen1017/tsk3/main.py
hw/hw09/Eugen1017/tsk1/core/logic.py
hw/hw09/Eugen1017/tsk1/main.py
hw/hw09/Eugen1017/tsk2/Rect_pygame.py

Hw09 eugen1017

---

hw/hw11/VadHk/task_1/main.py
hw/hw11/VadHk/task_2/main.py

Implement two functions: one to check if an entered age is even or odd, and another to map a number to a weekday. Both functions handle user input and exceptions.

hw11-VadHk

---

hw/hw07/alchemyks/tasks7_1/task1.py
hw/hw07/alchemyks/tasks7_1/task2.py
hw/hw07/alchemyks/tasks7_1/task3.py
hw/hw07/alchemyks/tasks7_3/practical_tasks.py

Цей пулреквест містить варіанти рішень завдань до теми 7, функціі.

Add practikal tasks for lecture  07. Functions

---

hw/hw08/f00a0a/task_08.1/main.py
hw/hw08/f00a0a/task_08.2/password.py
hw/hw08/f00a0a/task_08.3/main.py

Hw08 f00a0a

---

hw/hw09/VasiaZozulia/Rect_pygame.py
hw/hw09/VasiaZozulia/Task1.py

HW09 -  09.1 Practical task

---

hw/hw09/VikaLiakh/rect_pygame.py
hw/hw09/VikaLiakh/task1.py

Hello, here are 2 tasks from HW 9

 HW9 by VikaLiakh

---

hw/hw07/KShust/codewars.py
hw/hw07/KShust/task7_1_1.py
hw/hw07/KShust/task7_1_2.py
hw/hw07/KShust/task7_1_3.py

Adding solutions for tasks 7.1 and 7.3

HW07_Solutions for tasks 7.1 and 7.3

---

hw/hw11/ivze0115/Practical_Tasks_GitHub_Topic_11_1_task1.py
hw/hw11/ivze0115/Practical_Tasks_GitHub_Topic_11_1_task2.py

Add 11.1 Practical Tasks GitHub for ivze0115

HW11_1: Add 11.1 Practical Tasks GitHub for ivze0115

---

hw/hw07/Bak95/task3/Task 7.3 Github Outside.py

Додаю розв’язання завдання Task 7.3 (Github Outside) у відповідну директорію для HW07.

HW07: Add Task 7.3 Github Outside for Bak95

---

hw/hw11/Astronaunt-08/11.1_practical_task/task_1.py
hw/hw11/Astronaunt-08/11.1_practical_task/task_2.py

Додаю практичні завдання по темі 11

---

hw/hw10/ivansstef/10_1 Practical tasks  [GitHub]/task10_1_01.py
hw/hw10/ivansstef/10_1 Practical tasks  [GitHub]/task10_1_02.py
hw/hw10/ivansstef/10_1 Practical tasks  [GitHub]/task10_1_03.py

Додав   завдання Таски 10.1  з розідлу  10

Add 10.1  from ivansstef

---

hw/hw10/ivansstef/10_1 Practical tasks  [GitHub]/task10_1_01.py
hw/hw10/ivansstef/10_1 Practical tasks  [GitHub]/task10_1_02.py
hw/hw10/ivansstef/10_1 Practical tasks  [GitHub]/task10_1_03.py
hw/hw10/ivansstef/10_2 Practical tasks/Task_10_2_01.py
hw/hw10/ivansstef/10_2 Practical tasks/Task_10_2_02.py
hw/hw10/ivansstef/10_2 Practical tasks/Task_10_2_03.py
hw/hw10/ivansstef/10_2 Practical tasks/Task_10_2_04.py
hw/hw10/ivansstef/10_2 Practical tasks/Task_10_2_05.py
hw/hw10/ivansstef/10_2 Practical tasks/Task_10_2_06.py

Додав файли  -  6 шт. виконання завдання 10.2

Hw10 2 ivansstef

---

hw/hw07/IlliaChystoiev/07_3_CodeWars.py

hw07: add 07.3 Practical Task - IlliaChystoiev

---

hw/hw11/Serg-Pro/age_check.py
hw/hw11/Serg-Pro/day_of_week.py

Цей пулреквест мість файли практичних завдать для домашнього завдання HW11.

HW11: Add practical tasks for Serg-Pro

---

hw/hw09/f00a0a/task_1/game_script.py
hw/hw09/f00a0a/task_2/rect_pygame.py

Hw09 f00a0a

---

Zen.txt

Add my Zen of Python line on 117-119

HW6.1 - TEZv

---

hw/hw14/VasiaZozulia/functions.py
hw/hw14/VasiaZozulia/functions_with_errors.py
hw/hw14/VasiaZozulia/tests.py

HW14: Optional HomeWork [Topic 14] - VasiaZozulia

---

hw/hw14/omeliana-omeliana/functions.py
hw/hw14/omeliana-omeliana/functions_with_errors.py
hw/hw14/omeliana-omeliana/test_functions.py

HW14: Add Unittests for omeliana-omeliana

---

hw/hw11/inna-rst/Task_11_1.py
hw/hw11/inna-rst/Task_11_2.py

This pull request included solutions for practical task 11.1

HW11: Add solutions for practical task 11.1 - inna-rst

---

hw/hw11/lians/age.py
hw/hw11/lians/day.py

Added files for HW 11.1 [GitHub].

HW11.1 for Lians

---

hw/hw12/ivze0115/linguist.py
hw/hw12/ivze0115/test_linguist.py

Add SQLAlchemy Additional Practical Task for ivze0115

HW12: Add SQLAlchemy Additional Practical Task for ivze0115

---

hw/hw11/f00a0a/task_11.1.py
hw/hw11/f00a0a/task_11.2.py

Added hw task 11.1 and 11.2

---

hw/hw11/omeliana-omeliana/task_11_1_Age.py
hw/hw11/omeliana-omeliana/task_11_2_Week.py

Task 11.1.1 Age: even or odd
Task 11.1.2 Day of a week

HW11: Add Tasks 11.1 for omeliana-omeliana

---

hw/hw09/inna-rst/9.1_guess_number.py
hw/hw09/inna-rst/9.2_Rect_pygame.py

This pull request includes solutions for task 9.1 and 9.2.

HW09: Add solutions for task 9.1 and 9.2 - inna-rst

---

hw/hw11/VasiaZozulia/Task1.py
hw/hw11/VasiaZozulia/Task2.py

11.1 Practical Tasks / [GitHub] - Task1 and Task2 are done.

hw-11 - VasiaZozulia

---

hw/hw11/VikaLiakh/task1.py
hw/hw11/VikaLiakh/task2.py

HW 11 by VikaLiakh

---

hw/hw09/alchemyks/PracticalTask9_1/guess_the_number.py
hw/hw09/alchemyks/PracticalTask9_2/Rect_pygame.py

Цей пулреквест містить код для домашнього завдання HW09.

Practical task home work 9 is done alchemyks

---

hw/hw11/Eugen1017/hw11_1_1.py
hw/hw11/Eugen1017/hw11_1_2.py

HW11: Add Learn Git Branching screenshots for Eugen1017

HW11: Add Learn Git Branching screenshots for Eugen1017

---

hw/hw07/f00a0a/task_7.3/task_10_convert_boolean_values_to_strings_'yes'_or_'no’.py
hw/hw07/f00a0a/task_7.3/task_11_counting _sheep.py
hw/hw07/f00a0a/task_7.3/task_12_is_this_my_tail.py
hw/hw07/f00a0a/task_7.3/task_1_Jenny's_secret_message.py
hw/hw07/f00a0a/task_7.3/task_2_find_the_distance_between_two_points.py
hw/hw07/f00a0a/task_7.3/task_3_ no_yelling!.py
hw/hw07/f00a0a/task_7.3/task_4_convert_a_number_to_a_string.py
hw/hw07/f00a0a/task_7.3/task_5_reversing_words _in_a_string.py
hw/hw07/f00a0a/task_7.3/task_6_reverse_list_order.py
hw/hw07/f00a0a/task_7.3/task_7_multiples_of_3_or_5.py
hw/hw07/f00a0a/task_7.3/task_8_will_you_make_it.py
hw/hw07/f00a0a/task_7.3/task_9_.are_you_playing_banjo.py

updated hw07_task_3

---

hw/hw09/picter-max/task1.py
hw/hw09/picter-max/task2.py

Done practical tasks for 9 lesson

HW09: Done practical tasks for 9 lesson

---

hw/hw10/belikmaks/10.1/Task1.py
hw/hw10/belikmaks/10.1/Task2.py
hw/hw10/belikmaks/10.1/Task3.py
hw/hw10/belikmaks/10.2/Ball-super-ball.py
hw/hw10/belikmaks/10.2/Basic-subclasses-Adam-and-Eve.py
hw/hw10/belikmaks/10.2/Building Spheres.py
hw/hw10/belikmaks/10.2/Classy-classes.py
hw/hw10/belikmaks/10.2/Color-ghost.py
hw/hw10/belikmaks/10.2/Dynamic Classes.py
hw/hw11/belikmaks/task1.py
hw/hw11/belikmaks/task2.py
hw/hw12/belikmaks/linguist.py
hw/hw12/belikmaks/test.py

Homework 10 & 11 & optional 12

Homework 10 & 11 & optional 12

---

hw/hw14/inna-rst/functions.py
hw/hw14/inna-rst/functions_with_errors.py
hw/hw14/inna-rst/test.py

This pull request includes unit tests for 2 modules.

HW14: add unit tests for 2 modules optional task for inna-rst

---

mini_projects/VikaLiakh/Weather-Forecast/app.py
mini_projects/VikaLiakh/Weather-Forecast/file_handler.py
mini_projects/VikaLiakh/Weather-Forecast/requirements.txt
mini_projects/VikaLiakh/Weather-Forecast/weather_api.py

Weather Forecast project by VikaLiakh

---

mini_projects/f00a0a/demo_app.py
mini_projects/f00a0a/main_app.py

added micro project

---

hw/hw09/Vladislavit/Task_09.1.py
hw/hw09/Vladislavit/Task_09.2.py

Created game in task 1 and modefied code, so that the rectangle now doesnt extend beyond the program window

HW09: Done Tasks 09.1 and 09.2

---

hw/hw07/bherych/task7_1.py
hw/hw07/bherych/task7_2.py
hw/hw07/bherych/task7_3.py

Finished three tasks:
1. A function that returns the largest number out of two.
2. A small program that lets user calculate an area for triangle, rectangle, or circle.
3. A function that calculates number of characters in string.

HW07: Added three files with tasks for bherych

---

hw/hw08/yhalk/practical_task_08_3/functions.py
hw/hw08/yhalk/practical_task_08_3/main.py

The hw 08-3 is done
